
name: my prototype

# 觸發條件
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  - cron: "35 3 * * *" # At 23:50 on Thursday.
  - cron: "40 3 * * *"  # At 23:50 on day-of-month 24.
jobs:
  build:
    name: Set up environment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 38
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install Google Chrome # Using shell script to install Google Chrome
      run: |
        chmod +x ./scripts/InstallChrome.sh
        ./scripts/InstallChrome.sh  
    - name: Create a folder to save data
      run: 
        mkdir data   
    - name: Crawler
      run:
        python python_scripts/crawler/run.py
    - name: Send mail
      env:
        MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
        MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        MAIL_ADDRESS: ${{ secrets.MAIL_ADDRESS }}
        MAIL_TEST: ${{ secrets.MAIL_TEST }}
        GITHUB_JOB: ${{ github.job }}
        GITHUB_WORKFLOW: ${{ github.workflow }}
        GITHUB_REPO: ${{ github.repository }}
        JOB_STATUS: ${{ job.status }}
      run:
        python python_scripts/sender/run.py
    - name: Create exe # Using shell script to install Google Chrome
      run: |
        chmod +x ./scripts/create_exe.sh
    - name: Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with: 
        name: download
        path: dist